export const ACTION_TYPE = {
  //app
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_MODAL_OPEN: "SET_IS_MODAL_OPEN",
  SET_IS_PASSWORD_VISIBLE: "SET_IS_PASSWORD_VISIBLE",
  SET_IS_MENU_VISIBLE: "SET_IS_MENU_VISIBLE",
  SET_IS_SHOW_NOTIFICATION: "SET_IS_SHOW_NOTIFICATION",
  //products
  SET_PRODUCT: "SET_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCT_RATING: "SET_PRODUCT_RATING",
  SET_PRODUCT_REVIEWS: "SET_PRODUCT_REVIEWS",
  REMOVE_REVIEW: "REMOVE_REVIEW",
  //users
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  //cart
  SET_CART: "SET_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  UPDATE_CART: "UPDATE_CART",
  INCREASE_PRODUCT_COUNT: "INCREASE_PRODUCT_COUNT",
  DECREASE_PRODUCT_COUNT: "DECREASE_PRODUCT_COUNT",
  CLEAR_CART: "CLEAR_CART",
  //orders
  SET_ORDERS: "SET_ORDERS",
  CANCEL_ORDER: "CANCEL_ORDER",
  CLEAR_ORDERS: "CLEAR_ORDERS",
};
